import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Header } from "@/components/layout/Header";
import { Footer } from "@/components/layout/Footer";
import { QueryClient } from "@tanstack/react-query";
import Providers from "@/utils/providers";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en' className='h-full'>
      <body
        className={`${inter.variable} antialiased font-sans flex min-h-full flex-col`}
      >
        <Providers>
          <Header />
          <main className='flex-1 py-4'>{children}</main>
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
